name: Build and Deploy Docker Image

on:
  push:
    branches:
      - main  # You can change this to your default branch

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      # Check out the repository
      - name: Checkout code
        uses: actions/checkout@v2

      # Log in to DockerHub
      - name: Log in to Docker Hub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}

      # Build the Docker image
      - name: Build Docker image
        run: |
          docker build -t myusername/my-repo-name:$GITHUB_SHA .
          docker tag myusername/my-repo-name:$GITHUB_SHA myusername/my-repo-name:latest

      # Push the Docker image to Docker Hub
      - name: Push Docker image
        run: |
          docker push myusername/my-repo-name:$GITHUB_SHA
          docker push myusername/my-repo-name:latest
